defaults:
  - dataset: strict
  - model: base
  - _self_

hydra:
  job:
    chdir: false

root: ${hydra:runtime.cwd}

context_length: 512
vocab_size: 16384

paths:
  raw: ${root}/data/${dataset.slug}/raw
  prepped: ${root}/data/${dataset.slug}/prepped
  packed: ${root}/data/${dataset.slug}/packed
  pretokenized: ${root}/pretokenized/${dataset.slug}
  tokenizer: ${root}/tokenizers/tokenizer_${dataset.slug}.json

num_workers: 16
batch_size: 1000

tokenizer:
  min_frequency: 2
