defaults:
  - dataset: strict
  - model: base
  - trainer: default
  - samples: default
  - logging: wandb
  - _self_

hydra:
  job:
    chdir: false

root: ${hydra:runtime.cwd}

context_length: 512
vocab_size: 16384

paths:
  raw: ${root}/data/${dataset.slug}/raw
  pretokenized: ${root}/pretokenized/${dataset.slug}
  tokenizer: ${root}/tokenizers/tokenizer_${dataset.slug}.json
  checkpoints: ${root}/checkpoints/${dataset.slug}
  hf_export: ${root}/checkpoints/${dataset.slug}/hf

pretokenize:
  num_workers: 16
  batch_size: 1000

tokenizer:
  min_frequency: 2
